### ISSUE TITLE
FYI: This doesn't support years.

### ISSUE THREAD

**Issue by beinginorbit** [icyleaf/fastlane-plugin-humanable_build_number#1]
If you plan to use this plugin be aware that when the new years rolls in HockeyApp won't have your builds in order anymore as you are starting at a lower build number. This plugin needs the year as well IMHO at least if you intend for the build number to be infinitely sequential.

**Comment by icyleaf** [comment]
With Android App the greatest value Google Play allows for versionCode is `2100000000`, use year always overflow the maximum value, and same with iOS App. the correct build number format is `mmddHHMM`. See https://github.com/icyleaf/fastlane-plugin-humanable_build_number/blob/master/lib/fastlane/plugin/humanable_build_number/helper/humanable_build_number_helper.rb#L10

> BTW, README was updated. thanks
